FROM python:3.8-slim

RUN apt-get update 

WORKDIR /

RUN pip install torch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 -f https://download.pytorch.org/whl/cpu/torch_stable.html
RUN pip install timm==0.3.2 tensorboardX six 
RUN pip install numpy==1.22
RUN pip install submitit fairlearn kneed

RUN apt-get install -y ninja-build libopenblas-dev \
    xterm xauth openssh-server tmux mate-desktop-environment-core nano

RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*