kaggle: false
data_path: "./isic2020_challenge"
skin_color_csv: "./isic2020_challenge/ISIC_2020_full.csv"
output_dir: "./melanoma_output"
log_dir: "./melanoma_logs"
model: "convnext_tiny"
num_classes: 2
num_groups: 4
pretrained: true
freeze_model: false
in_22k: false
input_size: 224
drop_path: 0.1
test: true
batch_size: 2
epochs: 10
start_epoch: 0
update_freq: 1
ohem: false
ifw: true
recall_ce: false
focal_loss: false
domain_independent_loss: false
domain_discriminative_loss: true
conditional_accuracy: null
opt: "adamw"
opt_eps: 1.0e-08
opt_betas: null
lr: 0.0001
min_lr: 1.0e-06
weight_decay: 0.0001
weight_decay_end: 0.0001
clip_grad: null
warmup_epochs: 1
warmup_steps: -1
layer_decay: 1.0
oversample_malignant: false
undersample_benign: false
undersample_benign_ratio: -1
smoothing: 0.1
mixup: 0.0
cutmix: 0.0
cutmix_minmax: null
mixup_prob: 1.0
mixup_switch_prob: 0.5
mixup_mode: "batch"
cielab: true
skin_former: false
segment_out_skin: false
model_ema: false
model_ema_decay: 0.9999
model_ema_force_cpu: false
save_ckpt: true
save_ckpt_freq: 1
seed: 0
device: "cuda"
num_workers: 32
pin_mem: true
checkpoint: ""
use_amp: false
world_size: 1
local_rank: -1
dist_on_itp: false
distributed: false
dist_url: "env://"
