data_path: "C:/lumen_melanoma_classification/melanoma-classification/isic2020_challenge"
skin_color_csv: "C:/lumen_melanoma_classification/melanoma-classification/isic2020_challenge/ISIC_2020_full.csv"
model: "dinov2_vit_small"
in_22k: false
batch_size: 8
epochs: 10
input_size: 224
num_classes: 2
num_workers: 4
pretrained: true
log_dir: "./melanoma_logs"
warmup_epochs: 0
use_amp: false
lr: 0.01
mixup: 0.0
update_freq: 1
ifw: true
weight_decay: 0.0001
output_dir: "./melanoma_classifier_output"